/*
 * Copyright (c) 2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2020 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */
/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB17 (coord E9), U10[1]/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                      /* @} */
/* Symbols to be used with GPIO driver */
#define BOARD_GPIO_ACCEL_SDA_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_GPIO_ACCEL_SDA_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_GPIO_ACCEL_SDA_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_GPIO_ACCEL_SDA_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_GPIO_ACCEL_SDA_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTD8 (coord C9), U8[4]/U19[11]/I2C0_SCL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_GPIO_ACCEL_SCL_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_GPIO_ACCEL_SCL_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_GPIO_ACCEL_SCL_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_GPIO_ACCEL_SCL_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_GPIO_ACCEL_SCL_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
